spring:
  datasource:
    username: wanted
    password: password
    url: jdbc:mysql://localhost:3306/wanted?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
